apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs3219-task-a2
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hello-world
          # imagePullPolicy: Never
          ports:
            - containerPort: 80
